name: "✍️ Propose a prompt"
description: Write your prompt and let our team of writers create a story.
title: "✍️ [PROMPT] - <title>"
labels: [
  "prompt"
]
body:
  - type: textarea
    id: prompt
    attributes:
      label: "✒️Prompt🖊️"
      description: Write your proposed prompt
      placeholder: > 
        Example:
        The story must be one of the following genres (or a combination of them): Fantasy, Fiction, Horror, or Humor.
        Extra points if the story ends with an unexpected twist.
    validations:
      required: true
