name: PR Check

on:
  pull_request:
    types: ["opened", "reopened", "synchronize", "assigned", "labeled"]

permissions:
  contents: read

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
